name: CI

on:
  pull_request:
    branches:
      - '**'

jobs:
  ci:
    runs-on: ubuntu-20.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true

    steps:
      - uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version-file: './src/go.mod'
      
      - name: Build
        working-directory: ./src
        run: |
          go get .
          go build -v ./...

      - name: checks
        working-directory: ./src
        run: |
          go vet ./...
          go fmt ./...